
server:
  port: 8000
   
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/springboot_jihun?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: toor
  web:
    resources:
      static-locations:
      - classpath:/static/
      add-mappings: true
mybatis:
  mapper-locations:
  - /mappers/*.xml